/* Part of V3Code, distributed by KandD Labs LLC.
 * Existing copyright and license notices remain applicable.
 */
/*--------------------------------------------------------------------------------------
 *  Static (Model2Vec / potion-code-16M) embedder — runs INLINE in the Worker/DO,
 *  no queue, no GPU, no Workers-AI round-trip. Embedding is tokenize → look up a
 *  precomputed vector per token → weighted mean → L2-normalize: ~30k chunks/s on
 *  pure CPU. This is the same model the V3Code editor runs locally, so cloud and
 *  local vectors share one 256-dim space (the ensemble becomes trivial).
 *
 *  Two halves:
 *   1. TOKENIZER (this file's top half) — a byte-exact port of the potion-code-16M
 *      BERT-uncased tokenizer (BertNormalizer → BertPreTokenizer → WordPiece). Parity
 *      with the HuggingFace/@xenova reference is the ONE gate that decides everything
 *      (a mismatch silently corrupts every vector); test/potion-tokenizer.test.ts
 *      byte-checks it against fixtures generated by the editor's own tokenizer.
 *   2. EMBEDDER (added once the tokenizer passes) — loads the int8 vector table from
 *      R2 into a module-global and computes the vector. Model math mirrors the
 *      editor's staticEmbedder.ts encodeOne, verified against model2vec StaticModel.
 *--------------------------------------------------------------------------------------*/

// ── Unicode predicates (BERT tokenizer parity — mirror HF BasicTokenizer) ──────────────

/** \t \n \r and any Unicode space-separator (Zs) count as whitespace. */
function isWhitespace(ch: string): boolean {
	if (ch === ' ' || ch === '\t' || ch === '\n' || ch === '\r') return true;
	return /\p{Zs}/u.test(ch);
}

/** Control chars are stripped by clean_text — but \t \n \r are treated as whitespace,
 *  not control. Everything else in a Unicode "Other" category (Cc/Cf/Cs/Co) is control. */
function isControl(ch: string): boolean {
	if (ch === '\t' || ch === '\n' || ch === '\r') return false;
	return /\p{C}/u.test(ch);
}

/** HF _is_punctuation: the four ASCII punctuation bands (which include code symbols
 *  like = < > _ $ @ so they split into their own tokens) plus any Unicode P category. */
function isPunctuation(cp: number, ch: string): boolean {
	if ((cp >= 33 && cp <= 47) || (cp >= 58 && cp <= 64) || (cp >= 91 && cp <= 96) || (cp >= 123 && cp <= 126)) return true;
	return /\p{P}/u.test(ch);
}

/** CJK ideograph ranges — handle_chinese_chars pads each with spaces so every CJK
 *  char becomes its own token (matches BERT). */
function isChinese(cp: number): boolean {
	return (cp >= 0x4e00 && cp <= 0x9fff) || (cp >= 0x3400 && cp <= 0x4dbf) ||
		(cp >= 0x20000 && cp <= 0x2a6df) || (cp >= 0x2a700 && cp <= 0x2b73f) ||
		(cp >= 0x2b740 && cp <= 0x2b81f) || (cp >= 0x2b820 && cp <= 0x2ceaf) ||
		(cp >= 0xf900 && cp <= 0xfaff) || (cp >= 0x2f800 && cp <= 0x2fa1f);
}

/** BertNormalizer: clean_text → handle_chinese_chars → strip_accents → lowercase.
 *  potion-code-16M config: lowercase=true, strip_accents=null(→follows lowercase),
 *  clean_text=true, handle_chinese_chars=true. */
function bertNormalize(text: string): string {
	let cleaned = '';
	for (const ch of text) {
		const cp = ch.codePointAt(0)!;
		if (cp === 0 || cp === 0xfffd || isControl(ch)) continue; // clean_text drops these
		if (isWhitespace(ch)) { cleaned += ' '; continue; }
		if (isChinese(cp)) { cleaned += ` ${ch} `; continue; } // pad CJK
		cleaned += ch;
	}
	// strip_accents (NFD decompose, drop combining marks Mn) then lowercase.
	return cleaned.normalize('NFD').replace(/\p{Mn}/gu, '').toLowerCase();
}

/** BertPreTokenizer: split on whitespace, then peel each punctuation char into its
 *  own token (so `foo(bar)` → foo ( bar ) ). */
function bertPreTokenize(text: string): string[] {
	const out: string[] = [];
	for (const word of text.split(/\s+/)) {
		if (!word) continue;
		let cur = '';
		for (const ch of word) {
			if (isPunctuation(ch.codePointAt(0)!, ch)) {
				if (cur) { out.push(cur); cur = ''; }
				out.push(ch);
			} else {
				cur += ch;
			}
		}
		if (cur) out.push(cur);
	}
	return out;
}

/** WordPiece: greedy longest-match from the front; non-initial pieces carry the ##
 *  prefix; if any position can't be matched the WHOLE word is [UNK]. */
function wordPiece(word: string, vocab: Map<string, number>, unkId: number, maxChars = 100): number[] {
	const chars = [...word]; // codepoint-aware
	if (chars.length > maxChars) return [unkId];
	const out: number[] = [];
	let start = 0;
	while (start < chars.length) {
		let end = chars.length;
		let id = -1;
		while (start < end) {
			const piece = (start > 0 ? '##' : '') + chars.slice(start, end).join('');
			const hit = vocab.get(piece);
			if (hit !== undefined) { id = hit; break; }
			end--;
		}
		if (id === -1) return [unkId]; // unmatchable → whole word is UNK
		out.push(id);
		start = end;
	}
	return out;
}

/** Encode text → token ids (add_special_tokens=false), byte-exact with the potion
 *  reference. `vocab` maps token string → id; `unkId` is the [UNK] id. */
export function encodeIds(text: string, vocab: Map<string, number>, unkId: number): number[] {
	const ids: number[] = [];
	for (const word of bertPreTokenize(bertNormalize(text))) {
		const pieces = wordPiece(word, vocab, unkId);
		for (const p of pieces) ids.push(p);
	}
	return ids;
}

// ── Embedding math (Model2Vec StaticModel._encode_batch parity) ────────────────────────

/** The precomputed potion model as flat typed arrays. `mapping[id]` → row in
 *  `embeddings` (null = the id itself is the row); `weights[id]` → per-token weight
 *  (null = 1). `embeddings` is a flat [rows*dim] table — F32 (parity/reference) or
 *  Int8 (production, 4× smaller so it fits the 128MB isolate) with `scale` as the
 *  dequant factor (int8 value * scale ≈ f32 value; 0.998+ cosine). scale defaults
 *  to 1, which is a no-op for an F32 table. */
export interface StaticModel {
	mapping: Int32Array | null;
	weights: Float64Array | Float32Array | null;
	embeddings: Float32Array | Int8Array;
	scale?: number;
	dim: number;
	normalize: boolean;
	unkId: number;
	/** WordPiece vocab (token→id), packed in the R2 blob tail so model + tokenizer
	 *  travel together — no 61k-key JSON import to explode the Worker bundle. */
	vocab?: Map<string, number>;
}

/** How many leading tokens model2vec keeps (it truncates long inputs). */
export const MAX_TOKENS = 512;

/** Embed token ids → a dim-length vector: weighted mean of the per-token rows, then
 *  (if the model normalizes) L2-normalize. Unk tokens and negative rows are dropped,
 *  exactly like the editor's encodeOne / model2vec StaticModel. Allocation-light. */
export function embedVector(ids: number[], m: StaticModel): Float32Array {
	const { dim, embeddings, mapping, weights, normalize, unkId } = m;
	const scale = m.scale ?? 1; // int8 dequant factor; 1 = no-op for an F32 table
	const acc = new Float64Array(dim);
	let count = 0;
	const limit = Math.min(ids.length, MAX_TOKENS);
	for (let k = 0; k < limit; k++) {
		const id = ids[k];
		if (id === unkId) continue;
		const row = mapping ? mapping[id] : id;
		if (row < 0) continue;
		const w = (weights ? weights[id] : 1) * scale;
		const base = row * dim;
		for (let d = 0; d < dim; d++) acc[d] += embeddings[base + d] * w;
		count++;
	}
	const out = new Float32Array(dim);
	if (count === 0) return out;
	if (normalize) {
		let norm = 0;
		for (let d = 0; d < dim; d++) { acc[d] /= count; norm += acc[d] * acc[d]; }
		norm = Math.sqrt(norm) + 1e-32;
		for (let d = 0; d < dim; d++) out[d] = acc[d] / norm;
	} else {
		for (let d = 0; d < dim; d++) out[d] = acc[d] / count;
	}
	return out;
}

// ── Model loading (compact int8 blob, cached per isolate) ──────────────────────────────

/** Parse the packed int8 model blob. Little-endian layout:
 *    dim:u32 | V:u32 | rows:u32 | scale:f32 | normalize:u8 | unkId:u32
 *    mapping:i32[V] | weights:f32[V] | embeddings:i8[rows*dim]
 *  mapping/weights are copied (small, need alignment); the 16MB int8 table is a VIEW
 *  over the source buffer (no copy, no alignment needed) so peak memory stays ~one
 *  copy of the blob. */
export function parseStaticModel(buf: ArrayBuffer): StaticModel {
	const dv = new DataView(buf);
	const dim = dv.getUint32(0, true);
	const V = dv.getUint32(4, true);
	const rows = dv.getUint32(8, true);
	const scale = dv.getFloat32(12, true);
	const normalize = dv.getUint8(16) === 1;
	const unkId = dv.getUint32(17, true);
	let off = 21;
	const mapping = new Int32Array(buf.slice(off, off + V * 4)); off += V * 4;
	const weights = new Float32Array(buf.slice(off, off + V * 4)); off += V * 4;
	const embeddings = new Int8Array(buf, off, rows * dim); off += rows * dim;
	// Optional vocab tail: [u32 byteLen][utf8 JSON of {token: id}]. Absent in the
	// mini test blob (which embeds by id and needs no tokenizer).
	let vocab: Map<string, number> | undefined;
	if (off + 4 <= buf.byteLength) {
		const vlen = dv.getUint32(off, true);
		const json = new TextDecoder().decode(new Uint8Array(buf, off + 4, vlen));
		vocab = new Map(Object.entries(JSON.parse(json) as Record<string, number>));
	}
	return { mapping, weights, embeddings, scale, dim, normalize, unkId, vocab };
}

/** R2 object key for the packed potion model (bumped when the model/format changes). */
export const STATIC_MODEL_KEY = 'models/potion-code-16M-int8-v1.bin';

let cachedModel: StaticModel | null = null;
let loadInFlight: Promise<StaticModel> | null = null;

/** Load + cache the model from R2 for the lifetime of this isolate. Concurrent
 *  callers share one fetch (loadInFlight). Both the DO (index-time) and the Worker
 *  (query-time) call this against the BLOBS bucket. */
export function loadStaticModel(bucket: R2Bucket): Promise<StaticModel> {
	if (cachedModel) return Promise.resolve(cachedModel);
	if (!loadInFlight) {
		loadInFlight = (async () => {
			const obj = await bucket.get(STATIC_MODEL_KEY);
			if (!obj) throw new Error(`static model missing in R2: ${STATIC_MODEL_KEY}`);
			cachedModel = parseStaticModel(await obj.arrayBuffer());
			return cachedModel;
		})().catch(err => { loadInFlight = null; throw err; }); // let a failed load retry
	}
	return loadInFlight;
}

// ── One-call inline embedding (vocab comes from the loaded model) ───────────────────────

/** Embed one text with an already-loaded model: tokenize (model.vocab) → embed.
 *  Synchronous + fast (~microseconds); call loadStaticModel() once, then this per chunk. */
export function embedWith(text: string, m: StaticModel): Float32Array {
	if (!m.vocab) throw new Error('static model has no vocab (mini/test blob) — cannot embed text');
	return embedVector(encodeIds(text, m.vocab, m.unkId), m);
}

/** Convenience: load (cached) + embed. For the single query on the read path. */
export async function embedTextInline(text: string, bucket: R2Bucket): Promise<Float32Array> {
	return embedWith(text, await loadStaticModel(bucket));
}
