import { describe, expect, it } from 'vitest';
import { encodeIds } from '../src/embed/staticEmbedder.js';
import vocabJson from './fixtures-potion-vocab.json';
import fixtures from './fixtures-potion-tok.json';

/*--------------------------------------------------------------------------------------
 *  THE PARITY GATE. The potion static embedder is only trustworthy if our JS tokenizer
 *  produces the EXACT token ids the model was distilled against — a WordPiece mismatch
 *  silently corrupts every vector. Fixtures were generated by the editor's own
 *  @xenova/transformers tokenizer loading the cached potion-code-16M model, so this is
 *  a byte-check against ground truth, not a re-derivation.
 *--------------------------------------------------------------------------------------*/

const vocab = new Map<string, number>(Object.entries(vocabJson as Record<string, number>));
const unkId = vocab.get('[UNK]')!;

describe('potion tokenizer parity (BERT WordPiece)', () => {
	it('byte-matches the HF/editor reference on every fixture', () => {
		for (const { text, ids } of fixtures as Array<{ text: string; ids: number[] }>) {
			expect(encodeIds(text, vocab, unkId), `mismatch on ${JSON.stringify(text)}`).toEqual(ids);
		}
	});

	it('handles empty + whitespace-only input without throwing', () => {
		expect(encodeIds('', vocab, unkId)).toEqual([]);
		expect(encodeIds('   \t\n  ', vocab, unkId)).toEqual([]);
	});
});
